"""Generate docker-compose.yml for the whole stack.

Single-mount model: X -> /data for every service, plus X/Arr/<svc> -> /config.
All services join one bridge network and expose their WebUI on the host so any
LAN device can reach them. Ports/paths come from the generated .env.
"""

from __future__ import annotations

from pathlib import Path

from . import constants

HEADER = """# Generated by the ARR Stack Appliance installer -- do not edit by hand.
# Re-run the installer to regenerate. Values come from the sibling .env file.
#
# Control the whole stack from this directory:
#   docker compose up -d      # start everything
#   docker compose down       # stop everything
#   docker compose pull       # update images

name: arrstack

networks:
  arrstack:
    name: arrstack

services:
"""

# Common bits shared by the LinuxServer.io *Arr services + qBittorrent + Jellyfin.
_LSIO_COMMON = """    environment:
      - PUID=${{PUID}}
      - PGID=${{PGID}}
      - TZ=${{TZ}}
    volumes:
      - ${{DATA_PATH}}/Arr/{cfg}:/config
      - ${{DATA_PATH}}:/data
    networks:
      - arrstack
    restart: unless-stopped
"""


def _healthcheck(port: int, path: str = "/") -> str:
    # Pure-TCP probe via `nc`, which is present on every image in the stack
    # (busybox `nc` on Homepage, full `nc` on the LinuxServer/Jellyfin images).
    # The previous `bash -c '</dev/tcp/...'` probe failed permanently on Homepage,
    # which ships no bash -- leaving a healthy container marked "unhealthy".
    test = f"nc -z 127.0.0.1 {port} || exit 1"
    return (
        "    healthcheck:\n"
        f'      test: ["CMD-SHELL", "{test}"]\n'
        "      interval: 10s\n"
        "      timeout: 5s\n"
        "      retries: 30\n"
        "      start_period: 20s\n"
    )


def _service_block(name: str) -> str:
    svc = constants.SERVICES[name]
    up = name.upper()

    if name == "homepage":
        return (
            f"  {name}:\n"
            f"    image: ${{{up}_IMAGE}}\n"
            f"    container_name: {name}\n"
            "    environment:\n"
            "      - PUID=${PUID}\n"
            "      - PGID=${PGID}\n"
            "      - TZ=${TZ}\n"
            f"      - HOMEPAGE_ALLOWED_HOSTS=*\n"
            "    volumes:\n"
            "      - ${DATA_PATH}/Arr/homepage:/app/config\n"
            "      - ${DATA_PATH}/Arr/homepage/images:/app/public/images:ro\n"
            "      - ${DATA_PATH}:/data:ro\n"
            "      - /var/run/docker.sock:/var/run/docker.sock:ro\n"
            "    networks:\n"
            "      - arrstack\n"
            f"    ports:\n      - \"${{{up}_PORT}}:3000\"\n"
            "    restart: unless-stopped\n"
            + _healthcheck(3000)
            + "\n"
        )

    block = (
        f"  {name}:\n"
        f"    image: ${{{up}_IMAGE}}\n"
        f"    container_name: {name}\n"
    )

    if name == "qbittorrent":
        block += (
            "    environment:\n"
            "      - PUID=${PUID}\n"
            "      - PGID=${PGID}\n"
            "      - TZ=${TZ}\n"
            "      - WEBUI_PORT=8080\n"
            "    volumes:\n"
            "      - ${DATA_PATH}/Arr/qbittorrent:/config\n"
            "      - ${DATA_PATH}:/data\n"
            "    networks:\n      - arrstack\n"
            "    ports:\n"
            f"      - \"${{{up}_PORT}}:8080\"\n"
            "      - \"6881:6881\"\n"
            "      - \"6881:6881/udp\"\n"
            "    restart: unless-stopped\n"
            + _healthcheck(8080)
            + "\n"
        )
        return block

    if name == "jellyfin":
        block += _LSIO_COMMON.format(cfg="jellyfin")
        block += (
            "    ports:\n"
            f"      - \"${{{up}_PORT}}:8096\"\n"
            "    # Optional hardware transcoding (uncomment if you have an iGPU):\n"
            "    # devices:\n"
            "    #   - /dev/dri:/dev/dri\n"
            + _healthcheck(8096)
            + "\n"
        )
        return block

    if name == "jellyseerr":
        block += (
            "    environment:\n"
            "      - TZ=${TZ}\n"
            "    volumes:\n"
            "      - ${DATA_PATH}/Arr/jellyseerr:/app/config\n"
            "      - ${DATA_PATH}:/data:ro\n"
            "    networks:\n"
            "      - arrstack\n"
            "    ports:\n"
            f"      - \"${{{up}_PORT}}:5055\"\n"
            "    restart: unless-stopped\n"
            + _healthcheck(5055)
            + "\n"
        )
        return block

    # Prowlarr / Sonarr / Radarr / Bazarr
    internal_port = svc.port
    block += _LSIO_COMMON.format(cfg=name)
    block += (
        "    ports:\n"
        f"      - \"${{{up}_PORT}}:{internal_port}\"\n"
        + _healthcheck(internal_port)
        + "\n"
    )
    return block


def render_compose() -> str:
    parts = [HEADER]
    for name in constants.SERVICE_ORDER:
        parts.append(_service_block(name))
    return "".join(parts)


def write_compose(dest: Path) -> Path:
    dest = Path(dest)
    dest.write_text(render_compose())
    return dest
