"""Generate the `.env` file consumed by docker-compose.yml.

Holds host paths, PUID/PGID/TZ, ports and the generated qBittorrent web
password. Written with 0600 perms and git-ignored (contains a secret).
"""

from __future__ import annotations

import os
import secrets
import string
from pathlib import Path

from . import constants


def gen_password(length: int = 16) -> str:
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def default_puid_pgid():
    try:
        return os.getuid(), os.getgid()
    except AttributeError:  # Windows
        return 1000, 1000


def build_env(config: dict) -> dict:
    """config keys: data_path, tz, qbit_user, qbit_pass, puid, pgid, lan_subnet."""
    puid, pgid = config.get("puid"), config.get("pgid")
    if puid is None or pgid is None:
        puid, pgid = default_puid_pgid()

    env = {
        "DATA_PATH": config["data_path"],
        "PUID": str(puid),
        "PGID": str(pgid),
        "TZ": config.get("tz", "Etc/UTC"),
        "LAN_SUBNET": config.get("lan_subnet", "0.0.0.0/0"),
        "QBIT_USER": config.get("qbit_user", constants.DEFAULT_QBIT_USER),
        "QBIT_PASS": config.get("qbit_pass") or gen_password(),
    }
    for name in constants.SERVICE_ORDER:
        svc = constants.SERVICES[name]
        env[f"{name.upper()}_PORT"] = str(config.get(f"{name}_port", svc.port))
        env[f"{name.upper()}_IMAGE"] = config.get(f"{name}_image", svc.image)
    return env


def render_env(env: dict) -> str:
    lines = [
        "# Generated by the ARR Stack Appliance installer.",
        "# Contains secrets -- do not commit. Regenerate by re-running the installer.",
        "",
    ]
    for k, v in env.items():
        lines.append(f"{k}={v}")
    lines.append("")
    return "\n".join(lines)


def write_env(env: dict, dest: Path) -> Path:
    dest = Path(dest)
    dest.write_text(render_env(env))
    try:
        os.chmod(dest, 0o600)
    except OSError:
        pass
    return dest


def load_env(path: Path) -> dict:
    result = {}
    p = Path(path)
    if not p.exists():
        return result
    for line in p.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        result[k.strip()] = v.strip()
    return result
